import Logout from "@/images/icons/Logout";
import Delete from "@/images/icons/Delete";
import DashboardLogo from "@/images/icons/DashboardLogo";
import DashboardIcon from "@/images/icons/DashboardIcon";
import AppointmentIcon from "@/images/icons/AppointmentIcon"
import PatientIcon from "@/images/icons/PatientIcon";
import DoctorIcon from "@/images/icons/DoctorIcon"
import TestTubeIcon from "@/images/icons/TestTubeIcon"
import ReportsIcon from "@/images/icons/ReportsIcon"
import PaymentIcon from "@/images/icons/PaymentIcon"
import StaffIcon from "@/images/icons/StaffIcon"
import HolidayCalendarIcon from "@/images/icons/HolidayCalendarIcon"
import ResourceIcon from "@/images/icons/ResourcesIcon"
import SettingsIcon from "@/images/icons/SettingsIcon"
import EyeOpen from "@/images/icons/EyeOpen";
import EyeClosed from "@/images/icons/EyeClosed";
import Logo from "@/images/icons/Logo";
import Profile from "@/images/icons/Profile"
import ActivityLog from "@/images/icons/ActivityLog"
import Cross from "@/images/icons/Cross";
import Setting from "@/images/icons/Settings";
import Add from "@/images/icons/Add";
import PencilEdit from "@/images/icons/PencilEdit";
import ManageCenterIcon from "@/images/icons/ManageCenterIcon";
import BillingIcon from "@/images/icons/BillingIcon";
import TimeBasedDiscountIcon from "@/images/icons/TimeBasedDiscountIcon";
import ConfirmationIcon from "@/images/icons/ConfirmationIcon";
import WarningIcon from "@/images/icons/WarningIcon";

export { Logo, EyeOpen, EyeClosed, Logout, DashboardIcon, Delete, DashboardLogo, Profile, ActivityLog, Cross, Setting, Add, PencilEdit, PatientIcon, DoctorIcon, TestTubeIcon, ReportsIcon, PaymentIcon, StaffIcon, HolidayCalendarIcon, SettingsIcon, AppointmentIcon, ManageCenterIcon, BillingIcon, ResourceIcon, TimeBasedDiscountIcon, ConfirmationIcon, WarningIcon };